### ISSUE TITLE
simplyfoc library issue

### ISSUE THREAD

**Issue by wangxinghe88** [scottbez1/smartknob#140]
Askuric's simplyfoc project has been updated to 2.3.1 and there is changes in function's parameteres,  which will generate error in the code.
solution：
In the platfromio.ini file, lib_deps should be changed to:
askuric/Simple FOC@2.3.0

I think the typo "@^2.3.0" makes the version up to V2.3.1 unintentedly.

**Comment by Edo78** [comment]
I think the issue is in Askuric's simplyfoc ... if a breaking changes is introduced (like a change in function's parameters) then he should have followed semantic version rules and not just bump a patch

**Comment by runger1101001** [comment]
Yeah, sorry about that!

The changes were documented and announced, but we should pay attention to the version numbers as well.

I created a PR: https://github.com/scottbez1/smartknob/pull/142
this fixes the compile errors, but as I don't have a smartknob I can't test it out...
