### ISSUE TITLE
I've found the Gimbal Motor

### ISSUE THREAD

**Issue by Redstonehenge42** [scottbez1/smartknob#152]
:-)
https://www.sparkfun.com/products/20441
![grafik](https://github.com/scottbez1/smartknob/assets/122779181/cf9d9dae-1ab6-4b5b-8550-a62246f133e8)
![grafik](https://github.com/scottbez1/smartknob/assets/122779181/d4e659b7-7666-42fc-b88b-119267978937)
![grafik](https://github.com/scottbez1/smartknob/assets/122779181/cdcaacd7-c4a0-4b1c-add3-82500f2b8696)

**Comment by scottbez1** [comment]
Yes, this is already noted in the readme:
> Thanks to https://github.com/scottbez1/smartknob/issues/16#issuecomment-1094482805%5D, we were able to identify the likely original manufacturer, and recently SparkFun Electronics has been getting them produced and regularly [stocking them](https://www.sparkfun.com/products/20441)!

Cheers
