### ISSUE TITLE
openinput

### ISSUE THREAD

**Issue by perigoso** [scottbez1/smartknob#18]
Thinking of integrating something like this in our input device firmware project [openinput](https://github.com/openinput-fw)
Can think of couple applications for this like keyboards, and mouse scroll wheel, and stand alone ofcourse

That said the way it currently is wont integrate well (arduino and esp), so I will have to do something from scratch.

Yet I think it would be nice to integrate here the [openinput-protocol](https://openinput.readthedocs.io/projects/protocol/en/latest) for configurations and interactions, the protocol is under development, so feel free to suggest functions that would be useful for this so that they can be thought about and integrated

**Comment by scottbez1** [comment]
Cool, thanks for sharing!
