### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by reality-boy** [scottbez1/smartknob#19]
Sorry, this is not an issue at all.  I just wanted to say excellent work!  This is a very creative project. You basically made a force feedback steering wheel.  I'm a developer at iRacing.com, if your ever curious about making it work with DirectInput let me know.  And if you ever get it to a commercial state I would love to add it into our video game, our members would be ecstatic to have something like this to make brake bias adjustments.

**Comment by scottbez1** [comment]
Thanks so much! And yeah, it is basically a force feedback steering wheel. I don't have immediate plans to go commercial with this, but will keep that in mind if I do - thanks for reaching out!
