### ISSUE TITLE
How does the magnetic encoder work?

### ISSUE THREAD

**Issue by qsheeeeen** [scottbez1/smartknob#28]
This a an amazing work both in enginering and designing. I really apperiate it.
But there is one thing I couldn't understand. MountBase is covering the MT6701 sensor. Both are stationary. And I didn't see any magnet using in the CAD file. I could not figure out what magnet feild the  MT6701 is sensing. Maybe there is a donut shaped magnet attached to the rotor? Could you please explain it a littele bit? Maybe in your next video. Thanks in advance.

**Comment by C44Supra** [comment]
The motor has a small diametric ring magnet on the bottom.
