### ISSUE TITLE
How to solder strain gauges?

### ISSUE THREAD

**Issue by Merlin04** [scottbez1/smartknob#33]
Quick question only sort of related to your project - how did you solder the strain gauges? I bought some of a similar kind a while ago for a different project but I couldn't figure out how to reliably connect to the pads on the gauge without destroying it.

**Comment by VioSynthax** [comment]
You may have better luck with some low-temp solder. Consider looking for a bismuth based solder. Don't mix bismuth and lead based solder, you'll get bad joints! (bismuth + lead is basically chipquik, so it's great for desoldering, not so much for soldering.) Use a little flux, keep your temps low.
