### ISSUE TITLE
Without screen PCB, how can I test features? 

### ISSUE THREAD

**Issue by zinwalin** [scottbez1/smartknob#35]
I didn't receive all components, no strain gauge at the moment, when I touch pins on strain gauge position, the mode is changed. 

--------------------------------------------
Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html

--- Miniterm on COM3  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 271414342, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
use SENSOR_MT6701
MOT: Monitor enabled!
MOT: Init
MOT: Enable driver.
millilux: 165384.00
MOT: Align sensor.
MOT: Skip dir calib.
MOT: Skip offset calib.
millilux: 165470.39
MOT: No current sense.
MOT: Ready.
Press Y to run calibration
millilux: 165484.80
millilux: 165484.80
millilux: 165441.61
7.34
Got new config
millilux: 165441.61
millilux: 165441.61
millilux: 165441.61
----------------------------------------------------
![5f08e6c80fe435ee6123ec589e5500f](https://user-images.githubusercontent.com/5416196/160850135-41c13984-2901-4743-ac0e-4da783f78618.jpg)

**Comment by scottbez1** [comment]
Closing in favor of #36
