### ISSUE TITLE
Idea: The BLDC motor could greatly improve upon the 3D/XYZ-YPR mouse

### ISSUE THREAD

**Issue by RichardBronosky** [scottbez1/smartknob#39]
There are many projects that try to mechanically present an interface for users to input XYZ movement and Yaw Pitch Roll for interaction with models in 3D space. The use of BLDC motors in addition to or in place of potentiometers, rotary encoders, and similar electro-mechanical sensors could greatly improve the user experience ans simplify the mechanical design. Rather than having to find a mechanical device that was designed for the way the user intuitively wants to give input, the user could purchase a device that fits a much larger market and customize it through software to deliver the experience that allows each user to stay in flow and not be distracted by the hardware interface.

Note: This is constitutes *Prior Art*. The feature described is currently in development and offered freely to the public domain and may not be used in patents.

**Comment by Glodigit** [comment]
My project may be of relevance: https://hackaday.io/project/184181
