### ISSUE TITLE
3D Printing issue

### ISSUE THREAD

**Issue by zinwalin** [scottbez1/smartknob#40]
I sent STL/STP files to 3D Printing factory, they can't read models properly.  

The link is https://bezeklabs.autodesk360.com/g/shares/SH35dfcQT936092f0e4372570ef992887b79

Is there anything I did wrong with 3D models?

**Comment by scottbez1** [comment]
That's the Fusion 360 model. The latest STLs can be found here: https://github.com/scottbez1/smartknob/releases/tag/releases%2Fmechanical%2Fv185-dummy-tag

Worth noting, I have not tested those STLs yet; they include some changes made after my initial order so may not work.
