### ISSUE TITLE
Brushless driver

### ISSUE THREAD

**Issue by kryshac** [scottbez1/smartknob#42]
With which integrated could I replace `TMC6300-LA` but which one can I find on Aliexpress? (`DRV8316` is still not on Aliexpress)

**Comment by scottbez1** [comment]
In my research I didn't really find other good options for low voltage low current integrated drivers; TMC6300 is mostly in a class of its own at this point. So you'll likely need to purchase from on the of the big electronics distributors, of which Mouser and Farnell appear to currently have stock.
