### ISSUE TITLE
How to check whether HX711/Strain gauges has problem? 

### ISSUE THREAD

**Issue by zinwalin** [scottbez1/smartknob#48]
It's not working on my side, before fixed strain gauges on PCB, I just want to validate strain gauges is originally working with HX711. 

There's current on 6 pads for strain gauges, but no response(the screen keeps showing Unbounded No detents which is the mode by defaut) when I touched 4 strain gauges when powered. 

![image](https://user-images.githubusercontent.com/5416196/161887145-d84c958a-e558-43e8-b7ce-35864c07d292.png)

**Comment by scottbez1** [comment]
The strain gauge thresholds will need to be manually calibrated based on your physical assembly (every build will be different).

The code outputs a `HX711 reading` value to the serial console once per second by default. You can check that this changes when you touch a strain gauge.

Then once the strain gauges are permanently installed, you can get a reading when nothing is pressed and set this as the "lower" value, and then press down on the knob and get a reading there and set that as the "upper" value here: https://github.com/scottbez1/smartknob/blob/5c2a10428a7c4736a4aa2c93c831fbd3f2271b72/firmware/src/interface_task.cpp#L206-L207

**Comment by scottbez1** [comment]
Also, by the way, for testing the knob without the strain gauges, you can press [space] in the serial monitor to switch to the next mode in lieu of activating the strain gauges.

**Comment by zinwalin** [comment]
> Also, by the way, for testing the knob without the strain gauges, you can press [space] in the serial monitor to switch to the next mode in lieu of activating the strain gauges.

Yes. I get used to press space to change mode.

**Comment by zinwalin** [comment]
> The strain gauge thresholds will need to be manually calibrated based on your physical assembly (every build will be different).
> 
> The code outputs a `HX711 reading` value to the serial console once per second by default. You can check that this changes when you touch a strain gauge.
> 
> Then once the strain gauges are permanently installed, you can get a reading when nothing is pressed and set this as the "lower" value, and then press down on the knob and get a reading there and set that as the "upper" value here:
> 
> https://github.com/scottbez1/smartknob/blob/5c2a10428a7c4736a4aa2c93c831fbd3f2271b72/firmware/src/interface_task.cpp#L206-L207

Hi Scott, your reply saved lots of time, there's no console output for HX711 reading by default, cause the lower and upper values are too high on my side, so the logic for HX711 is not run.  After I lower the values, it works.  Appreciated for your reminders.

**Comment by scottbez1** [comment]
Glad to have helped!
