### ISSUE TITLE
proto, handheld and handheld_tdisplay do not compile on master branch.

### ISSUE THREAD

**Issue by mcmadhatter** [scottbez1/smartknob#49]
Currently on the master branch only the view  target will compile.

Environment        Status    Duration
-----------------  --------  ------------
proto              FAILED    00:00:04.469
view               SUCCESS   00:00:43.869
handheld           FAILED    00:00:07.100
handheld_tdisplay  FAILED    00:00:06.988

The handheld and handheld mods seem to be a bit behind master, but do compile ok.

**Comment by shirogeek** [comment]
Same here. I kept trying to figure out why that is until I saw this issue posted here.

**Comment by scottbez1** [comment]
Yeah those are vestiges of previous experiments, I need to clean them up. `view` is what you want.
