### ISSUE TITLE
Problem: Motor stuck in 7 positions.

### ISSUE THREAD

**Issue by caoge12138** [scottbez1/smartknob#79]
I've built up one these days but facing the problem that motor will stuck in some position when rotate over the limit, Like this:

https://user-images.githubusercontent.com/23009776/175996585-cefe18b5-a027-40bc-b8ae-00d9dcefb015.mp4

Is there some mistake of the build?
THX!

**Comment by winking324** [comment]
You can try to calibrate at startup by press `shift + y` and write the calibrated data back into the code, `zero_electric_offset` in `motor_task.cpp`, and I solved similar problems like this.

**Comment by scottbez1** [comment]
Yep, this is most likely a calibration issue, causing the motor driver outputs to be out of phase with the physical rotor. Following the calibration procedure as described above https://github.com/scottbez1/smartknob/issues/79#issuecomment-1211477028 should resolve it.
