### ISSUE TITLE
Problem: Reboot when the switch is toggled(On/Off Strong detent)

### ISSUE THREAD

**Issue by winking324** [scottbez1/smartknob#88]
Hi, I have a problem for help:

https://user-images.githubusercontent.com/7922054/184053479-88745095-48f6-4034-8b0e-0ed9638df1a7.mp4

I have no idea for how to debug this problem, can someone give me some tips?

Thank you so much.

**Comment by lordeleren** [comment]
Looks to me like the motor is trying to draw more current than there is supply of. Forcing the ESP to reboot. Have you tried a bigger powerbrick?

**Comment by winking324** [comment]
Thank you so much for saving me!!!! 👍👍👍👍👍
